[package]
name = "echo"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.2.0"
cpal = "0.15.3"
earshot = "0.1.0"
hound = "3.5.1"
itertools = "0.13.0"
jack = "0.13.0"
regex = "1.11.1"
rubato = "0.16.1"
whisper-rs = "0.13.2"


[profile.release]
debug = true
